# Generated by Django 5.2.5 on 2025-09-10 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='class_attachments/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'txt', 'jpg', 'jpeg', 'png', 'gif'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Class Attachment',
                'verbose_name_plural': 'Class Attachments',
                'db_table': 'class_attachments',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('se221', 'SE221'), ('cs221', 'CS221'), ('ee201', 'EE201'), ('math101', 'MATH101'), ('phy201', 'PHY201'), ('is301', 'IS301')], max_length=10)),
                ('venue', models.CharField(choices=[('acb-lh1', 'ACB-LH1'), ('acb-lh2', 'ACB-LH2'), ('acb-lh3', 'ACB-LH3'), ('acb-lh4', 'ACB-LH4'), ('acb-lh5', 'ACB-LH5'), ('acb-lh6', 'ACB-LH6'), ('acb-lh7', 'ACB-LH7'), ('fsce-lh1', 'FSCE-LH1'), ('fsce-lh2', 'FSCE-LH2')], max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Class Schedule',
                'verbose_name_plural': 'Class Schedules',
                'db_table': 'class_schedules',
                'ordering': ['-created_at'],
            },
        ),
    ]
