# Generated by Django 5.2.5 on 2025-09-10 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True)),
                ('alarm_minutes_before', models.IntegerField(choices=[(5, '5 minutes before'), (10, '10 minutes before'), (15, '15 minutes before'), (20, '20 minutes before'), (30, '30 minutes before'), (60, '1 hour before')], default=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_settings', to='classes.classschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alarm Setting',
                'verbose_name_plural': 'Alarm Settings',
                'db_table': 'alarm_settings',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'class_schedule')},
            },
        ),
    ]
