# Generated by Django 5.2.5 on 2025-09-10 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alarmsettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmsettings',
            name='alarm_minutes_before',
            field=models.IntegerField(choices=[(5, '5 minutes before'), (10, '10 minutes before'), (15, '15 minutes before'), (20, '20 minutes before'), (30, '30 minutes before'), (60, '1 hour before'), (120, '2 hours before'), (180, '3 hours before')], default=20),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('alarm', 'Alarm Notification'), ('reminder', 'Reminder Notification'), ('test', 'Test Notification')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='classes.classschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'db_table': 'notification_logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
